config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  # get 'lists/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resources :lists, only: [:index, :show, :new, :create]

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :movie_id, :scope => [:list_id]
  validates_length_of :comment, minimum: 6, allow_blank: false
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    # @bookmark = @list.movies.find(params[:movie_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @list, :notice => "Task Deleted"
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New movie</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%# f.association :bookmarks %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-light mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/lists/index.html.erb
<%# <h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p> %>
<%# <p style="background-image: url('banner.avif');"> %>
<%# <div class="card-category"
  style="background-image: url('.avif')"
> %>
<%# image_tag "banner.avif", alt: "cinema", width: 200, class: "card-img" %>
<%# <div class="card-img-overlay"> %>
  <div class="container">
    <h1 class="card-title mt-20">Save any kind of movies</h1>
    <%= link_to "add a new list", new_list_path, class: "btn btn-primary"%> <br><br>
    <div class="row justify-content-center">
      <ul>
      <div class="row">
        <% @lists.each do |list| %>
          <%# <div class="container"> %>
          <div class="col-3">
            <div class="card">
              <%= image_tag "drama.avif", alt: "cinema", width: 200, class: "card-img" %>
                <div class="card-img-overlay">
                  <%= link_to list.name, list_path(list.id) %><br>
                </div>
            </div>
          </div>
        <% end %>
      </div>
      </ul>
    </div>
  </div>
<%# </div> %>

app/views/lists/new.html.erb
<h1>Create a new list</h1>
<!-- app/views/restaurants/_form.html.erb -->
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<%= link_to "back to the list", lists_path, class: "btn btn-success"%><br><br>
<%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-primary"%><br>

<p><strong></strong></p>
<ul class="list-group">
  <div class="row">
    <% @list.movies.each do |movie| %>
    <% bookmark = Bookmark.find_by(movie: movie, list: @list) %>
      <div class="col-12 col-sm-6 col-lg-3 p-3">
        <div class="card"  style="width: 18rem;">
          <%= image_tag movie.poster_url, alt: "cinema", width: 200, class: "card-img" %>
          <div class="card-body">
            <h5 class="card-title"><strong><%= movie.title %></strong></h5>
            <p class="card-text"><%= movie.overview %></p>
            <p class="card-text">Rating: <%= movie.rating %></p>
            <%= button_to "delete", list_bookmark_path(@list, bookmark), method: :delete, class: "btn btn-warning"%>
          </div>
        </div>
      </div>
  <% end %>
  </div>
    <%# raise %>
    <%# link_to 'Destroy', list_bookmark_path(@bookmark), method: :delete %>
    <%# link_to "delete", list_bookmark_path(@list, bookmark.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want" } %>
</ul>
<br>